/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packagee.AppContext;
import packagee.dto.AppointmentDTO;
import packagee.dto.DoctorDTO;
import packagee.dto.HospitalizationDTO;
import packagee.dto.PatientDTO;
import packagee.dto.UserDTO;
import packagee.model.AppointmentType;
import packagee.model.Prescription;
import packagee.model.Specialty;
import packagee.response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class DoctorView extends javax.swing.JFrame {

    private int x, y;
    private final AppContext appContext;
    private final UserDTO currentUser;
    private final long doctorId;

    public DoctorView(UserDTO user, long doctorId) {
        initComponents();
        this.appContext = AppContext.getInstance();
        this.currentUser = user;
        this.doctorId = doctorId;
        refreshDoctorViewData();
        if ("admin".equals(user.getType()))
            BackButton.setVisible(true);
        else    
            BackButton.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new packagee.PanelRound();
        panelRound2 = new packagee.PanelRound();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        DoctorTabbed = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        TotalRadButton = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AppoimentsTable = new javax.swing.JTable();
        PendingRadButton = new javax.swing.JRadioButton();
        LogoutButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        PatientComboBox = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LastnameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LicenseNumField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AssignedOffField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ConfirmField = new javax.swing.JTextField();
        specialityComboBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AcceptMedBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        AcceptMedButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RescheduleBox = new javax.swing.JComboBox<>();
        AcceptRescheduleButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        NewTimeField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ReasonField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CompleteAppoBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CompleteButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        DateEntryHospiField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        DurationHospiField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HospitalizationObsArea = new javax.swing.JTextArea();
        GenerateHospiButton = new javax.swing.JButton();
        RequestComboBox = new javax.swing.JComboBox<>();
        HospiRequestRadButton = new javax.swing.JRadioButton();
        PatientIDHospiRadButton = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        DiagnosisArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        ObservationArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        RecommendTreatMentArea = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        FollowUpIndicationsArea = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        CancelHospiButton = new javax.swing.JButton();
        PatientIdComboBox = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        ReasonForHospiArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        MedicationNameField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        DoseField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        AdminRouteField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        FrecuencyField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        TreatmentDurationField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        AdditionalInstrucField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        PrescribeMedicationTable = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        PrescribeButton = new javax.swing.JButton();
        AppoIdBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("DOCTOR VIEW");

        BackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BackButton))
        );

        TotalRadButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        TotalRadButton.setText("Total appointments");
        TotalRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalRadButtonActionPerformed(evt);
            }
        });

        AppoimentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        jScrollPane3.setViewportView(AppoimentsTable);

        PendingRadButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PendingRadButton.setText("Pending appointments");
        PendingRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingRadButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(TotalRadButton)
                            .addGap(18, 18, 18)
                            .addComponent(PendingRadButton))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalRadButton)
                    .addComponent(PendingRadButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(23, 23, 23))
        );

        DoctorTabbed.addTab("Appointments visualization", jPanel4);

        PatientComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel38.setText("Patient");

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(PatientTable);

        SearchButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(PatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SearchButton)
                .addGap(601, 601, 601))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(PatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(SearchButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        DoctorTabbed.addTab("History Appointments of a patient", jPanel5);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Firstname");

        FirstNameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Lastname");

        LastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Specialty");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setText("License Number");

        LicenseNumField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setText("Assigned office");

        UserField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("User");

        AssignedOffField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel11.setText("Password confirmation");

        ConfirmField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        specialityComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        specialityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        SaveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(LastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(specialityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(LicenseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AssignedOffField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(SaveButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(ConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(specialityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LicenseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignedOffField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(ConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SaveButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        DoctorTabbed.addTab("Modify info", jPanel3);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Appointment ID");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel13.setText("Accept medical appointment");

        AcceptMedBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptMedBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AcceptMedButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptMedButton.setText("Accept");
        AcceptMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptMedButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Reschedule medical appointment");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Appointment");

        RescheduleBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RescheduleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        AcceptRescheduleButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptRescheduleButton.setText("Accept");
        AcceptRescheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRescheduleButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("New time appointment");

        NewTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Reason for appointment");

        ReasonField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Complete medical appointment");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Appointment");

        CompleteAppoBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteAppoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Diagnosis");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Observations");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Recommended treatment");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Follow-up indication");

        CompleteButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteButton.setText("Complete");
        CompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Hospitalization");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Reason for hospitalization");

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Date of entry");

        DateEntryHospiField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Estimated duration");

        DurationHospiField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Observations");

        HospitalizationObsArea.setColumns(20);
        HospitalizationObsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationObsArea.setRows(5);
        jScrollPane1.setViewportView(HospitalizationObsArea);

        GenerateHospiButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenerateHospiButton.setText("Generate");
        GenerateHospiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateHospiButtonActionPerformed(evt);
            }
        });

        RequestComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        HospiRequestRadButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospiRequestRadButton.setText("Requests");

        PatientIDHospiRadButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientIDHospiRadButton.setText("Patient ID");

        DiagnosisArea.setColumns(20);
        DiagnosisArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DiagnosisArea.setRows(5);
        jScrollPane6.setViewportView(DiagnosisArea);

        ObservationArea.setColumns(20);
        ObservationArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ObservationArea.setRows(5);
        jScrollPane7.setViewportView(ObservationArea);

        RecommendTreatMentArea.setColumns(20);
        RecommendTreatMentArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RecommendTreatMentArea.setRows(5);
        jScrollPane8.setViewportView(RecommendTreatMentArea);

        FollowUpIndicationsArea.setColumns(20);
        FollowUpIndicationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FollowUpIndicationsArea.setRows(5);
        jScrollPane9.setViewportView(FollowUpIndicationsArea);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CancelHospiButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelHospiButton.setText("Cancel");
        CancelHospiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelHospiButtonActionPerformed(evt);
            }
        });

        PatientIdComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        ReasonForHospiArea.setColumns(20);
        ReasonForHospiArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonForHospiArea.setRows(5);
        jScrollPane10.setViewportView(ReasonForHospiArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(AcceptMedButton)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(AcceptMedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(RescheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(NewTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(ReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(AcceptRescheduleButton)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(CompleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(CompleteAppoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateEntryHospiField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DurationHospiField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CancelHospiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerateHospiButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(HospiRequestRadButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PatientIDHospiRadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PatientIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(CompleteAppoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CompleteButton)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(AcceptMedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(AcceptMedButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(RescheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(NewTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(ReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(AcceptRescheduleButton)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospiRequestRadButton)
                    .addComponent(PatientIDHospiRadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(DateEntryHospiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(DurationHospiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateHospiButton)
                    .addComponent(CancelHospiButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DoctorTabbed.addTab("Request/Appointments", jPanel1);

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel31.setText("Appointment ID");

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel32.setText("Medication name");

        MedicationNameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel33.setText("Dose");

        DoseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel34.setText("Administration route");

        AdminRouteField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel35.setText("Frecuency");

        FrecuencyField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel36.setText("Treatment duration");

        TreatmentDurationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel37.setText("Additional instructions");

        AdditionalInstrucField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PrescribeMedicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PrescribeMedicationTable);

        AddButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PrescribeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PrescribeButton.setText("Prescribe");
        PrescribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescribeButtonActionPerformed(evt);
            }
        });

        AppoIdBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppoIdBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AppoIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TreatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdditionalInstrucField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FrecuencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(MedicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdminRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(PrescribeButton)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(MedicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(DoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(AdminRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton)
                    .addComponent(AppoIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(TreatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(AdditionalInstrucField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(FrecuencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(PrescribeButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        DoctorTabbed.addTab("Prescribe medications", jPanel2);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoctorTabbed))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorTabbed))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void PendingRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingRadButtonActionPerformed
        TotalRadButton.setSelected(false);
        loadDoctorAppointments(true);
    }//GEN-LAST:event_PendingRadButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (!hasValidSelection(specialityComboBox)) {
            showError("Selecciona una especialidad.");
            return;
        }
        try {
            Response<?> response = appContext.getDoctorController().updateDoctor(
                    doctorId,
                    UserField.getText(),
                    FirstNameField.getText(),
                    LastnameField.getText(),
                    LicenseNumField.getText(),
                    AssignedOffField.getText(),
                    getSelectedSpecialty().name(),
                    PasswordField.getText(),
                    ConfirmField.getText()
            );
            if (response.isSuccess()) {
                refreshDoctorViewData();
                clearDoctorForm();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Revisa la información del doctor antes de guardar.");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        openLoginView();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        openAdminView();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CancelHospiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelHospiButtonActionPerformed
        if (!hasValidSelection(RequestComboBox)) {
            showError("Selecciona una hospitalización.");
            return;
        }
        try {
            Response<?> response = appContext.getHospitalizationController().denyOrCancelHospitalization(
                    RequestComboBox.getItemAt(RequestComboBox.getSelectedIndex())
            );
            if (response.isSuccess()) {
                refreshDoctorViewData();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Selecciona una hospitalización válida.");
        }
    }//GEN-LAST:event_CancelHospiButtonActionPerformed

    private void GenerateHospiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateHospiButtonActionPerformed
        if (!canSubmitDoctorHospitalization()) {
            return;
        }
        try {
            Response<?> response;
            if (HospiRequestRadButton.isSelected()) {
                response = appContext.getHospitalizationController().approveHospitalization(
                        RequestComboBox.getItemAt(RequestComboBox.getSelectedIndex()),
                        doctorId,
                        "IMC",
                        HospitalizationObsArea.getText()
                );
            } else {
                response = appContext.getHospitalizationController().createHospitalizationByPatient(
                        parseSelectedId(PatientIdComboBox.getItemAt(PatientIdComboBox.getSelectedIndex())),
                        doctorId,
                        DateEntryHospiField.getText(),
                        ReasonForHospiArea.getText(),
                        HospitalizationObsArea.getText()
                );
            }

            if (response.isSuccess()) {
                refreshDoctorViewData();
                clearHospitalizationForm();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Revisa los datos de hospitalización antes de continuar.");
        }
    }//GEN-LAST:event_GenerateHospiButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (!hasValidSelection(PatientComboBox)) {
            showError("Selecciona un paciente.");
            return;
        }
        loadPatientAppointmentHistory(parseSelectedId(PatientComboBox.getItemAt(PatientComboBox.getSelectedIndex())));
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void TotalRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalRadButtonActionPerformed
        PendingRadButton.setSelected(false);
        loadDoctorAppointments(false);
    }//GEN-LAST:event_TotalRadButtonActionPerformed

    private void AcceptMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptMedButtonActionPerformed
        if (!hasValidSelection(AcceptMedBox)) {
            showError("Selecciona una cita.");
            return;
        }
        try {
            Response<?> response = appContext.getAppointmentController().acceptAppointment(
                    AcceptMedBox.getItemAt(AcceptMedBox.getSelectedIndex())
            );
            if (response.isSuccess()) {
                refreshDoctorViewData();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Selecciona una cita válida.");
        }
    }//GEN-LAST:event_AcceptMedButtonActionPerformed

    private void CompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteButtonActionPerformed
        if (!hasValidSelection(CompleteAppoBox)) {
            showError("Selecciona una cita.");
            return;
        }
        try {
            Response<?> response = appContext.getAppointmentController().completeAppointment(
                    CompleteAppoBox.getItemAt(CompleteAppoBox.getSelectedIndex()),
                    DiagnosisArea.getText(),
                    ObservationArea.getText(),
                    RecommendTreatMentArea.getText(),
                    FollowUpIndicationsArea.getText()
            );
            if (response.isSuccess()) {
                refreshDoctorViewData();
                clearCompletionForm();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Selecciona una cita válida.");
        }
    }//GEN-LAST:event_CompleteButtonActionPerformed

    private void PrescribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescribeButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) PrescribeMedicationTable.getModel();
        model.setRowCount(0);
        clearPrescriptionForm();
    }//GEN-LAST:event_PrescribeButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (!canSubmitPrescription()) {
            return;
        }
        try {
            String appointmentId = AppoIdBox.getItemAt(AppoIdBox.getSelectedIndex());
            Response<packagee.dto.PrescriptionDTO> response = appContext.getAppointmentController().prescribeMedications(
                    appointmentId,
                    MedicationNameField.getText(),
                    parseDoubleValue(DoseField.getText()),
                    AdminRouteField.getText(),
                    parseIntValue(TreatmentDurationField.getText()),
                    AdditionalInstrucField.getText(),
                    parseIntValue(FrecuencyField.getText())
            );
            if (response.isSuccess()) {
                addPrescriptionRow(appointmentId);
                clearPrescriptionForm();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Revisa dosis, frecuencia y duración antes de agregar el medicamento.");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AcceptRescheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRescheduleButtonActionPerformed
        if (!hasValidSelection(RescheduleBox)) {
            showError("Selecciona una cita.");
            return;
        }
        try {
            Response<?> response = appContext.getAppointmentController().rescheduleAppointment(
                    RescheduleBox.getItemAt(RescheduleBox.getSelectedIndex()),
                    NewTimeField.getText(),
                    ReasonField.getText()
            );
            if (response.isSuccess()) {
                refreshDoctorViewData();
                clearRescheduleForm();
                showMessage(response.getMessage());
            } else {
                showError(response.getMessage());
            }
        } catch (RuntimeException ex) {
            showError("Revisa la nueva hora y el motivo de reprogramación.");
        }
    }//GEN-LAST:event_AcceptRescheduleButtonActionPerformed

    private void loadDoctorAppointments(boolean onlyPending) {
        Response<List<AppointmentDTO>> response = appContext.getDoctorController().getAppointments(doctorId, onlyPending);
        DefaultTableModel model = (DefaultTableModel) AppoimentsTable.getModel();
        model.setRowCount(0);
        if (response.isSuccess() && response.getData() != null) {
            for (AppointmentDTO appointment : response.getData()) {
                model.addRow(new Object[]{
                    appointment.getId(),
                    appointment.getDatetime().toString(),
                    appointment.getPatientName(),
                    formatSpecialty(appointment.getSpecialty()),
                    formatAppointmentType(appointment.getType()),
                    appointment.getStatus().name()
                });
            }
        }
    }

    private void loadPatientAppointmentHistory(long patientIdSelection) {
        Response<List<AppointmentDTO>> response = appContext.getPatientController().getAppointments(patientIdSelection);
        DefaultTableModel model = (DefaultTableModel) PatientTable.getModel();
        model.setRowCount(0);
        if (response.isSuccess() && response.getData() != null) {
            for (AppointmentDTO appointment : response.getData()) {
                model.addRow(new Object[]{
                    appointment.getId(),
                    appointment.getDatetime().toString(),
                    appointment.getDoctorName(),
                    formatSpecialty(appointment.getSpecialty()),
                    formatAppointmentType(appointment.getType()),
                    appointment.getStatus().name()
                });
            }
        }
    }

    private Specialty getSelectedSpecialty() {
        String specialtyValue = specialityComboBox.getItemAt(specialityComboBox.getSelectedIndex());
        return Specialty.valueOf(specialtyValue.replaceAll(" &", "").replaceAll(" ", "_"));
    }

    private long parseLongValue(String value) {
        return Long.parseLong(value.trim());
    }

    private int parseIntValue(String value) {
        return Integer.parseInt(value.trim());
    }

    private double parseDoubleValue(String value) {
        return Double.parseDouble(value.trim());
    }

    private void openLoginView() {
        LoginView login = new LoginView();
        this.setVisible(false);
        login.setVisible(true);
    }

    private void openAdminView() {
        AdminView admin = new AdminView(currentUser);
        this.setVisible(false);
        admin.setVisible(true);
    }

    private void refreshDoctorViewData() {
        loadDoctorProfile();
        loadDoctorAppointments(false);
        loadPatientOptions();
        loadAppointmentSelectors();
        loadHospitalizationSelectors();
    }

    private void loadDoctorProfile() {
        Response<DoctorDTO> response = appContext.getDoctorController().getDoctorInfo(doctorId);
        if (response.isSuccess() && response.getData() != null) {
            DoctorDTO doctor = response.getData();
            FirstNameField.setText(doctor.getFirstname());
            LastnameField.setText(doctor.getLastname());
            LicenseNumField.setText(doctor.getLicenceNumber());
            AssignedOffField.setText(doctor.getAssignedOffice());
            UserField.setText(doctor.getUsername());
            specialityComboBox.setSelectedItem(formatSpecialty(doctor.getSpecialty()));
        }
    }

    private void loadPatientOptions() {
        resetComboBox(PatientComboBox);
        resetComboBox(PatientIdComboBox);
        Response<List<PatientDTO>> response = appContext.getPatientController().getAllPatients();
        if (response.isSuccess() && response.getData() != null) {
            for (PatientDTO patient : response.getData()) {
                String option = formatPatientOption(patient);
                PatientComboBox.addItem(option);
                PatientIdComboBox.addItem(option);
            }
        }
    }

    private void loadAppointmentSelectors() {
        resetComboBox(AcceptMedBox);
        resetComboBox(RescheduleBox);
        resetComboBox(CompleteAppoBox);
        resetComboBox(AppoIdBox);
        Response<List<AppointmentDTO>> response = appContext.getDoctorController().getAppointments(doctorId, false);
        if (response.isSuccess() && response.getData() != null) {
            for (AppointmentDTO appointment : response.getData()) {
                String appointmentId = appointment.getId();
                AcceptMedBox.addItem(appointmentId);
                RescheduleBox.addItem(appointmentId);
                CompleteAppoBox.addItem(appointmentId);
                AppoIdBox.addItem(appointmentId);
            }
        }
    }

    private void loadHospitalizationSelectors() {
        resetComboBox(RequestComboBox);
        Response<List<HospitalizationDTO>> response = appContext.getHospitalizationController().getRequestedHospitalizations();
        if (response.isSuccess() && response.getData() != null) {
            for (HospitalizationDTO hospitalization : response.getData()) {
                RequestComboBox.addItem(hospitalization.getId());
            }
        }
    }

    private void addPrescriptionRow(String appointmentId) {
        DefaultTableModel model = (DefaultTableModel) PrescribeMedicationTable.getModel();
        model.addRow(new Object[]{
            appointmentId,
            MedicationNameField.getText(),
            DoseField.getText(),
            AdminRouteField.getText(),
            TreatmentDurationField.getText(),
            AdditionalInstrucField.getText(),
            FrecuencyField.getText()
        });
    }

    private void resetComboBox(javax.swing.JComboBox<String> comboBox) {
        comboBox.removeAllItems();
        comboBox.addItem("Select one");
    }

    private boolean hasValidSelection(javax.swing.JComboBox<String> comboBox) {
        Object selected = comboBox.getSelectedItem();
        return selected != null && !"Select one".equals(selected.toString());
    }

    private String formatPatientOption(PatientDTO patient) {
        return patient.getId() + " - " + patient.getFirstname() + " " + patient.getLastname();
    }

    private String formatSpecialty(Specialty specialty) {
        return specialty.name().replace("_", " & ");
    }

    private String formatAppointmentType(AppointmentType type) {
        return type == AppointmentType.IN_PERSON ? "In person" : "Virtual";
    }

    private boolean canSubmitDoctorHospitalization() {
        if (HospiRequestRadButton.isSelected()) {
            return hasValidSelection(RequestComboBox) || showValidation("Selecciona una solicitud de hospitalización.");
        }
        if (PatientIDHospiRadButton.isSelected()) {
            return hasValidSelection(PatientIdComboBox) || showValidation("Selecciona un paciente.");
        }
        return showValidation("Selecciona el tipo de hospitalización a procesar.");
    }

    private boolean canSubmitPrescription() {
        return hasValidSelection(AppoIdBox) || showValidation("Selecciona una cita.");
    }

    private boolean validateDoctorProfileForm() {
        if (FirstNameField.getText().trim().isEmpty()) {
            showError("El nombre del doctor no puede estar vacío.");
            return false;
        }
        if (!isValidPersonName(FirstNameField.getText())) {
            showError("El nombre del doctor solo puede contener letras y espacios.");
            return false;
        }
        if (LastnameField.getText().trim().isEmpty()) {
            showError("El apellido del doctor no puede estar vacío.");
            return false;
        }
        if (!isValidPersonName(LastnameField.getText())) {
            showError("El apellido del doctor solo puede contener letras y espacios.");
            return false;
        }
        if (!hasValidSelection(specialityComboBox)) {
            showError("Selecciona una especialidad.");
            return false;
        }
        if (LicenseNumField.getText().trim().isEmpty()) {
            showError("La licencia médica no puede estar vacía.");
            return false;
        }
        if (AssignedOffField.getText().trim().isEmpty()) {
            showError("La oficina asignada no puede estar vacía.");
            return false;
        }
        if (UserField.getText().trim().isEmpty()) {
            showError("El usuario no puede estar vacío.");
            return false;
        }
        return true;
    }

    private boolean validateDoctorHospitalizationForm() {
        if (HospiRequestRadButton.isSelected()) {
            return hasValidSelection(RequestComboBox) || showValidation("Selecciona una solicitud de hospitalización.");
        }
        if (PatientIDHospiRadButton.isSelected()) {
            if (!hasValidSelection(PatientIdComboBox)) {
                showError("Selecciona un paciente.");
                return false;
            }
            if (DateEntryHospiField.getText().trim().isEmpty()) {
                showError("La fecha de ingreso no puede estar vacía.");
                return false;
            }
            if (ReasonForHospiArea.getText().trim().isEmpty()) {
                showError("El motivo de hospitalización no puede estar vacío.");
                return false;
            }
            return true;
        }
        showError("Selecciona el tipo de hospitalización a procesar.");
        return false;
    }

    private boolean validatePrescriptionForm() {
        if (!hasValidSelection(AppoIdBox)) {
            showError("Selecciona una cita.");
            return false;
        }
        if (MedicationNameField.getText().trim().isEmpty()) {
            showError("El nombre del medicamento no puede estar vacío.");
            return false;
        }
        if (DoseField.getText().trim().isEmpty()) {
            showError("La dosis no puede estar vacía.");
            return false;
        }
        if (AdminRouteField.getText().trim().isEmpty()) {
            showError("La vía de administración no puede estar vacía.");
            return false;
        }
        if (TreatmentDurationField.getText().trim().isEmpty()) {
            showError("La duración del tratamiento no puede estar vacía.");
            return false;
        }
        if (FrecuencyField.getText().trim().isEmpty()) {
            showError("La frecuencia no puede estar vacía.");
            return false;
        }
        return true;
    }

    private boolean validateRescheduleForm() {
        if (!hasValidSelection(RescheduleBox)) {
            showError("Selecciona una cita.");
            return false;
        }
        if (NewTimeField.getText().trim().isEmpty()) {
            showError("La nueva hora no puede estar vacía.");
            return false;
        }
        if (ReasonField.getText().trim().isEmpty()) {
            showError("El motivo de reprogramación no puede estar vacío.");
            return false;
        }
        return true;
    }

    private boolean showValidation(String message) {
        showError(message);
        return false;
    }

    private boolean isValidPersonName(String value) {
        return value != null && value.trim().matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$");
    }

    private long parseSelectedId(String value) {
        if (value == null || "Select one".equals(value)) {
            return -1;
        }
        int separatorIndex = value.indexOf(" - ");
        if (separatorIndex < 0) {
            return parseLongValue(value);
        }
        return parseLongValue(value.substring(0, separatorIndex));
    }

    private void clearDoctorForm() {
        PasswordField.setText("");
        ConfirmField.setText("");
    }

    private void clearRescheduleForm() {
        if (RescheduleBox.getItemCount() > 0) {
            RescheduleBox.setSelectedIndex(0);
        }
        NewTimeField.setText("");
        ReasonField.setText("");
    }

    private void clearHospitalizationForm() {
        if (RequestComboBox.getItemCount() > 0) {
            RequestComboBox.setSelectedIndex(0);
        }
        if (PatientIdComboBox.getItemCount() > 0) {
            PatientIdComboBox.setSelectedIndex(0);
        }
        ReasonForHospiArea.setText("");
        DateEntryHospiField.setText("");
        DurationHospiField.setText("");
        HospitalizationObsArea.setText("");
    }

    private void clearCompletionForm() {
        if (CompleteAppoBox.getItemCount() > 0) {
            CompleteAppoBox.setSelectedIndex(0);
        }
        DiagnosisArea.setText("");
        ObservationArea.setText("");
        RecommendTreatMentArea.setText("");
        FollowUpIndicationsArea.setText("");
    }

    private void clearPrescriptionForm() {
        if (AppoIdBox.getItemCount() > 0) {
            AppoIdBox.setSelectedIndex(0);
        }
        MedicationNameField.setText("");
        DoseField.setText("");
        AdminRouteField.setText("");
        FrecuencyField.setText("");
        TreatmentDurationField.setText("");
        AdditionalInstrucField.setText("");
    }

    private void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AcceptMedBox;
    private javax.swing.JButton AcceptMedButton;
    private javax.swing.JButton AcceptRescheduleButton;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AdditionalInstrucField;
    private javax.swing.JTextField AdminRouteField;
    private javax.swing.JComboBox<String> AppoIdBox;
    private javax.swing.JTable AppoimentsTable;
    private javax.swing.JTextField AssignedOffField;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelHospiButton;
    private javax.swing.JComboBox<String> CompleteAppoBox;
    private javax.swing.JButton CompleteButton;
    private javax.swing.JTextField ConfirmField;
    private javax.swing.JTextField DateEntryHospiField;
    private javax.swing.JTextArea DiagnosisArea;
    private javax.swing.JTabbedPane DoctorTabbed;
    private javax.swing.JTextField DoseField;
    private javax.swing.JTextField DurationHospiField;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextArea FollowUpIndicationsArea;
    private javax.swing.JTextField FrecuencyField;
    private javax.swing.JButton GenerateHospiButton;
    private javax.swing.JRadioButton HospiRequestRadButton;
    private javax.swing.JTextArea HospitalizationObsArea;
    private javax.swing.JTextField LastnameField;
    private javax.swing.JTextField LicenseNumField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField MedicationNameField;
    private javax.swing.JTextField NewTimeField;
    private javax.swing.JTextArea ObservationArea;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JComboBox<String> PatientComboBox;
    private javax.swing.JRadioButton PatientIDHospiRadButton;
    private javax.swing.JComboBox<String> PatientIdComboBox;
    private javax.swing.JTable PatientTable;
    private javax.swing.JRadioButton PendingRadButton;
    private javax.swing.JButton PrescribeButton;
    private javax.swing.JTable PrescribeMedicationTable;
    private javax.swing.JTextField ReasonField;
    private javax.swing.JTextArea ReasonForHospiArea;
    private javax.swing.JTextArea RecommendTreatMentArea;
    private javax.swing.JComboBox<String> RequestComboBox;
    private javax.swing.JComboBox<String> RescheduleBox;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JRadioButton TotalRadButton;
    private javax.swing.JTextField TreatmentDurationField;
    private javax.swing.JTextField UserField;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private packagee.PanelRound panelRound1;
    private packagee.PanelRound panelRound2;
    private javax.swing.JComboBox<String> specialityComboBox;
    // End of variables declaration//GEN-END:variables
}
